services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/conf.prod/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django
    networks:
      - nginx_network

